### ISSUE TITLE
Segmentation fault on Linux

### ISSUE THREAD

**Issue by RoelVdP** [nickhodge/SharpSimpleNLG#12]
I want to try and use NLG for SQL generation. Any tips welcome. Also am seeing this issue:

Steps to reproduce (on Linux Mint 20 x64):

sudo apt install nuget
sudo snap install --classic dotnet-sdk
dotnet new console --output NLG
dotnet add NLG package SharpSimpleNLG --version 1.3.0
dotnet run --project NLG
cd NLG/bin/Debug/net5.0

$ ./NLG
Segmentation fault

Any idea?

GDB doesn't help much (how do build with debug symbols?):

Reading symbols from ./NLG...
(No debugging symbols found in ./NLG)
Core was generated by `./NLG'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f19e9eadbc0 in ?? ()
(gdb) bt
#0  0x00007f19e9eadbc0 in ?? ()
#1  0x00007f19e9982ff9 in dl_vdso_vsym (name=0x7f19e9a678c4 "__vdso_time") at ../sysdeps/unix/sysv/linux/dl-vdso.h:52
#2  time_ifunc () at ../sysdeps/unix/sysv/linux/time.c:38
#3  0x00007f19e9c8f33a in ?? () from /snap/core18/current/lib64/ld-linux-x86-64.so.2
#4  0x00007f19e9c86327 in ?? () from /snap/core18/current/lib64/ld-linux-x86-64.so.2
#5  0x00007f19e9c9cf50 in ?? () from /snap/core18/current/lib64/ld-linux-x86-64.so.2
#6  0x00007f19e9c84128 in ?? () from /snap/core18/current/lib64/ld-linux-x86-64.so.2
#7  0x00007f19e9c83098 in ?? () from /snap/core18/current/lib64/ld-linux-x86-64.so.2
#8  0x0000000000000001 in ?? ()
#9  0x00007ffcd034e486 in ?? ()
#10 0x0000000000000000 in ?? ()

**Comment by RoelVdP** [comment]
Any feedback ? Thank you

**Comment by nickhodge** [comment]
I dont use this in my day job .. nor Linux ... so it is going to have to go into the queue for the out of hours time .. which is filled with some other life events right now.

Feel free to download the source and debug. 

Could be related to .NET Core 5 vs. .NET Standard Libraries. Could be pathing. I just dont know and dont have the time
